name: Update Flipper Application Catalog

on:
  push:
    branches:
      - main
    paths:
      - 'application.fam'

jobs:
  update-catalog:
    runs-on: ubuntu-latest

    env:
      BRANCH_PREFIX: zacharyweiss/
      APP_NAME: magspoof
      APP_FOLDER: GPIO
      CATALOG_REPO: zacharyweiss/flipper-application-catalog
      CATALOG_UPSTREAM: flipperdevices/flipper-application-catalog
      CATALOG_FOLDER: flipper-application-catalog
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: ${{ env.APP_NAME }}
        
    - name: Get fap_version
      id: fap_version
      run: |
        cd $APP_NAME
        fap_version_raw=$(grep -oP '(?<=fap_version=\()\d+, \d+(?=\))' application.fam)
        v_major=$(echo $fap_version_raw | cut -d "," -f 1 | xargs)
        v_minor=$(echo $fap_version_raw | cut -d "," -f 2 | xargs)
        echo "v_major=$v_major" >> "$GITHUB_ENV"
        echo "v_minor=$v_minor" >> "$GITHUB_ENV"
        echo "branch_name=$BRANCH_PREFIX$APP_NAME_v$v_major.$v_minor" >> "$GITHUB_ENV"
        
    - name: Fork Flipper Application Catalog
      uses: actions/checkout@v4
      with:
        repository: ${{ env.CATALOG_REPO }}
        path: ${{ env.CATALOG_FOLDER }}
        
    - name: Create Branch
      run: |
        cd $CATALOG_FOLDER
        git checkout -b "$branch_name"
        git remote set-url origin "https://x-access-token:${{ secrets.CATALOG_UPDATE_TOKEN }}@github.com/$CATALOG_REPO.git"
        git remote add upstream "https://x-access-token:${{ secrets.CATALOG_UPDATE_TOKEN }}@github.com/$CATALOG_UPSTREAM.git"
        git fetch upstream main
        git remote -v
        git rebase --autosquash --autostash "upstream/main"
        

    - name: Update manifest.yml
      run: |
        manifest_path=applications/$APP_FOLDER/$APP_NAME/manifest.yml
        echo "manifest_path=$manifest_path" > "$GITHUB_ENV"
        touch $CATALOG_FOLDER/$manifest_path
        echo "commit_sha: ${{ github.sha }}" >> $CATALOG_FOLDER/$manifest_path

    - name: Commit & Push
      run: |
        cd $CATALOG_FOLDER
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add applications/GPIO/magspoof/manifest.yml
        git commit -m "Update magspoof manifest with commit ${{ github.sha }}"
        git push --force origin "$branch_name"


    
#    - name: Create Pull Request
#      id: cpr
#      uses: peter-evans/create-pull-request@v6
#      with:
#        token: ${{ secrets.CATALOG_UPDATE_TOKEN }}
#        path: ${{ env.CATALOG_FOLDER }}
#        commit-message: Update report
#        branch: ${{ env.branch_name }}
#        # base: 
#       delete-branch: true
#        title: '[Example] Update'
#        body: |
#          Update report
#          - Auto-generated by [create-pull-request][1]
#        draft: false
